from setuptools import setup

setup(name='AutoPower',
      version='0.0',
      description='AutoPower',
      url='https://github.com/florpi/AutoPower',
      install_requires=['camb',
                        'future',
                        'h5py',
                        'jupyter',
                        'matplotlib',
                        'numpy',
                        'pandas',
                        'pyDOE',
                        'scikit-learn',
                        'scipy',
                        'seaborn',
                        'torch',
                        'tensorboard',
                        'tqdm'],
      packages=['autopower'],
      zip_safe=False)
